version: "3.8"

services:
  mysqldb:
    build: ./db
    container_name: mysqldb
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./ideathon
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mysqldb
    command:
      bash -c "python wait_mysql.py &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

